# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  #pull_request:
    #branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@master
      - name: Install Dependencies
        run: npm install --force
      - name: Build App
        run: npm run build
        env:
          VUE_APP_MAIN_APP_URL: "https://nertivia.net/"
          VUE_APP_SOCKET_URL: "https://nertivia.net"
          VUE_APP_FETCH_PREFIX: "https://nertivia.net/api"
          VUE_APP_NERTIVIA_CDN: "https://media.nertivia.net/"
          VUE_APP_CAPTCHA_SITE_KEY: "8babbac4-8758-4347-84d4-0ff321e821bc"
          VUE_APP_TWEMOJI_LOCATION: "https://nertivia.net/twemojis/"
          VUE_APP_IMAGE_PROXY_URL: "//media.nertivia.net/proxy.php?url="
          VUE_APP_FCM_API_KEY: "AIzaSyBYRykWjjPicFkaiJ49C8GbUmbZUmJeWOg"
          VUE_APP_FCM_AUTH_DOMAIN: "dotted-clover-231410.firebaseapp.com"
          VUE_APP_FCM_DATABASE_URL: "https://dotted-clover-231410.firebaseio.com"
          VUE_APP_FCM_PROJECT_ID: "dotted-clover-231410"
          VUE_APP_FCM_STORAGE_BUCKET: "dotted-clover-231410.appspot.com"
          VUE_APP_FCM_SENDER_ID: "858269624186"
          VUE_APP_FCM_APP_ID: "1:858269624186:web:a3193c0b82097a41d918c3"    
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: /var/www/nertivia.net
          
          
          
          
  
